from app import create_app
from models import db, Book

app = create_app()

with app.app_context():
    db.drop_all()
    db.create_all()

    sample_books = [
        {
            "title": "Python编程：从入门到实践",
            "author": "Eric Matthes",
            "isbn": "9787115428028",
            "category": "编程",
            "description": "一本针对初学者的Python编程入门书籍，内容涵盖Python基础语法、面向对象编程、项目实践等。",
            "total_copies": 5,
            "available_copies": 3,
        },
        {
            "title": "深入理解计算机系统",
            "author": "Randal E. Bryant",
            "isbn": "9787111544937",
            "category": "计算机",
            "description": "从程序员的视角详细阐述计算机系统的本质概念，涵盖计算机底层原理。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "算法导论",
            "author": "Thomas H. Cormen",
            "isbn": "9787111407010",
            "category": "科学",
            "description": "全面介绍算法的经典教材，涵盖算法设计与分析。",
            "total_copies": 4,
            "available_copies": 4,
        },
        {
            "title": "活着",
            "author": "余华",
            "isbn": "9787506365437",
            "category": "文学",
            "description": "讲述了农村人福贵悲惨的人生遭遇，是一部具有史诗品质的作品。",
            "total_copies": 6,
            "available_copies": 5,
        },
        {
            "title": "人类简史：从动物到上帝",
            "author": "尤瓦尔·赫拉利",
            "isbn": "9787508647357",
            "category": "历史",
            "description": "从认知革命、农业革命到科学革命，讲述人类如何登上食物链顶端。",
            "total_copies": 3,
            "available_copies": 1,
        },
        {
            "title": "三体",
            "author": "刘慈欣",
            "isbn": "9787536692930",
            "category": "小说",
            "description": "中国科幻里程碑之作，讲述地球文明与三体文明的生死博弈。",
            "total_copies": 8,
            "available_copies": 6,
        },
        {
            "title": "教育学",
            "author": "王道俊",
            "isbn": "9787107250028",
            "category": "教育",
            "description": "师范院校公共课教育学教材，系统阐述教育基本理论。",
            "total_copies": 4,
            "available_copies": 2,
        },
        {
            "title": "艺术的故事",
            "author": "贡布里希",
            "isbn": "9787807463726",
            "category": "艺术",
            "description": "概括地叙述了从最早的洞窟绘画到当今的实验艺术的发展历程。",
            "total_copies": 3,
            "available_copies": 3,
        },
        {
            "title": "经济学原理",
            "author": "曼昆",
            "isbn": "9787301150894",
            "category": "经济",
            "description": "经济学入门经典教材，用通俗易懂的语言介绍经济学基本概念。",
            "total_copies": 5,
            "available_copies": 4,
        },
        {
            "title": "苏菲的世界",
            "author": "乔斯坦·贾德",
            "isbn": "9787506395168",
            "category": "哲学",
            "description": "以小说的形式，通过一名哲学导师向一个叫苏菲的女孩传授哲学知识的故事。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "史蒂夫·乔布斯传",
            "author": "沃尔特·艾萨克森",
            "isbn": "9787508630069",
            "category": "传记",
            "description": "苹果公司创始人乔布斯的官方传记，讲述其传奇一生。",
            "total_copies": 5,
            "available_copies": 2,
        },
        {
            "title": "数学之美",
            "author": "吴军",
            "isbn": "9787115428029",
            "category": "数学",
            "description": "用通俗的语言介绍数学在计算机科学和日常生活中的应用。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "时间简史",
            "author": "史蒂芬·霍金",
            "isbn": "9787535732309",
            "category": "物理",
            "description": "探索时间和空间奥秘的科普经典，讲述宇宙的起源与命运。",
            "total_copies": 6,
            "available_copies": 5,
        },
        {
            "title": "寂静的春天",
            "author": "蕾切尔·卡森",
            "isbn": "9787544763004",
            "category": "化学",
            "description": "环境保护运动的奠基之作，讲述化学农药对环境的危害。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "物种起源",
            "author": "查尔斯·达尔文",
            "isbn": "9787100071864",
            "category": "生物",
            "description": "奠定进化论基础的科学巨著，阐述自然选择学说。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "黄帝内经",
            "author": "佚名",
            "isbn": "9787117139014",
            "category": "医学",
            "description": "中国最早的医学典籍，奠定了人体生理、病理、诊断及治疗的认识基础。",
            "total_copies": 3,
            "available_copies": 1,
        },
        {
            "title": "论法的精神",
            "author": "孟德斯鸠",
            "isbn": "9787100090032",
            "category": "法律",
            "description": "法国启蒙思想家孟德斯鸠的代表作，系统阐述三权分立学说。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "心理学与生活",
            "author": "理查德·格里格",
            "isbn": "9787115371775",
            "category": "心理",
            "description": "心理学入门经典教材，将心理学理论与日常生活紧密结合。",
            "total_copies": 5,
            "available_copies": 4,
        },
        {
            "title": "乡土中国",
            "author": "费孝通",
            "isbn": "9787208095861",
            "category": "社会",
            "description": "中国社会学经典著作，深入分析中国基层社会结构与文化特征。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "文明的冲突与世界秩序的重建",
            "author": "塞缪尔·亨廷顿",
            "isbn": "9787501192717",
            "category": "政治",
            "description": "国际政治领域的经典著作，提出文明冲突论。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "孙子兵法",
            "author": "孙武",
            "isbn": "9787101052732",
            "category": "军事",
            "description": "中国古代最著名的兵书，世界三大兵书之一。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "徐霞客游记",
            "author": "徐霞客",
            "isbn": "9787101057416",
            "category": "地理",
            "description": "明代地理学家徐霞客的游记，记录了中国的山川地理风貌。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "平行宇宙",
            "author": "加来道雄",
            "isbn": "9787536679139",
            "category": "天文",
            "description": "讲述宇宙学前沿理论，探索多重宇宙的可能性。",
            "total_copies": 3,
            "available_copies": 1,
        },
        {
            "title": "贝多芬传",
            "author": "罗曼·罗兰",
            "isbn": "9787530209934",
            "category": "音乐",
            "description": "音乐巨人贝多芬的传记，展现其不屈的精神与艺术成就。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "认识电影",
            "author": "路易斯·贾内梯",
            "isbn": "9787506287104",
            "category": "电影",
            "description": "电影入门经典教材，全面介绍电影艺术的各个方面。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "论摄影",
            "author": "苏珊·桑塔格",
            "isbn": "9787532744107",
            "category": "摄影",
            "description": "摄影理论经典文集，探讨摄影的本质与文化意义。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "舌尖上的中国",
            "author": "中央电视台",
            "isbn": "9787511229359",
            "category": "美食",
            "description": "记录中国各地美食文化，展现中华饮食的博大精深。",
            "total_copies": 5,
            "available_copies": 4,
        },
        {
            "title": "孤独星球：中国旅行指南",
            "author": "Lonely Planet",
            "isbn": "9787503181435",
            "category": "旅行",
            "description": "全球最权威的旅行指南品牌出品的中国旅行指南。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "足球经济学",
            "author": "西蒙·库珀",
            "isbn": "9787508624068",
            "category": "运动",
            "description": "从经济学角度分析足球运动的有趣现象。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "游戏改变世界",
            "author": "简·麦戈尼格尔",
            "isbn": "9787213049422",
            "category": "游戏",
            "description": "探讨游戏化如何改变现实世界的工作与生活。",
            "total_copies": 4,
            "available_copies": 3,
        },
        {
            "title": "日本漫画论",
            "author": "夏目房之介",
            "isbn": "9787301238884",
            "category": "漫画",
            "description": "系统分析日本漫画的发展历史与艺术特色。",
            "total_copies": 3,
            "available_copies": 2,
        },
        {
            "title": "安徒生童话",
            "author": "安徒生",
            "isbn": "9787020046850",
            "category": "童话",
            "description": "丹麦作家安徒生的童话集，世界儿童文学的经典。",
            "total_copies": 6,
            "available_copies": 5,
        },
        {
            "title": "唐诗三百首",
            "author": "蘅塘退士",
            "isbn": "9787101068290",
            "category": "诗歌",
            "description": "中国流传最广的唐诗选本，收录唐代诗人的经典作品。",
            "total_copies": 5,
            "available_copies": 4,
        },
    ]

    for book_data in sample_books:
        if not Book.query.filter_by(isbn=book_data["isbn"]).first():
            book = Book(**book_data)
            db.session.add(book)

    db.session.commit()
    print(f"Sample data seeded successfully! Total books: {len(sample_books)}")
